# Generated by Django 4.0.2 on 2022-03-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='left_file_upload',
            field=models.IntegerField(default=0),
        ),
    ]
